### PR TITLE
Fix sidebar styles

### PR DESCRIPTION
**Pull request by emilyannemoses**
Issue # 1 Fox sidebar styles and font

I changed the sidebar css file so that all ul elements are now circles

I changed the sidebar css file to include h3 elements to be the same font.

I resolved the rubocop issues regarding space between operators in the sidebar 

All other files that were changed were related to the issue I encountered when bundle installing the gems for this project. I had to install a newer Ruby version and use it as my default so I could begin resolving further issues in this project. All other file changes are related to that initial issue.

### CODE REVIEW

**Comment by justincastilla** [comment]
66 files are unnecessarly changed
What issue number does this address?
What did you do to resolve this issue?

**Comment by emilyannemoses** [comment]
Issue # 1 Fox sidebar styles and font

I changed the sidebar css file so that all ul elements are now circles

I changed the sidebar css file to include h3 elements to be the same font.

I resolved the rubocop issues regarding space between operators in the sidebar

All other files that were changed were related to the issue I encountered when bundle installing the gems for this project. I had to install a newer Ruby version and use it as my default so I could begin resolving further issues in this project. All other file changes are related to that initial issue.

**Comment by justincastilla** [comment]
This will fix the issue -- but the real question is why and what was broken in the first place. For instance, why do all the other lists work just fine. Spaces between operators in the sidebar are not stated in the issue, so they don't need to be addressed.

**Comment by emilyannemoses** [comment]
Since I was running a version of Ruby less than 2.2.3 as this project requires, it wouldn't install a gem and required me to install Ruby 2.2.3 and use it as default so that's the base reason for the initial break.

There's a line in the lab that says to do rubocop for every issue to make sure there aren't any problems but I will be sure to make that a different branch next time so as not to confuse it with the specific issue at hand

**Pull request closed without merging**
