### PR TITLE
Fixed Issue #1: Inconsistent Sidebar Styles

### PR DESCRIPTION
**Pull request by samuel1008**
changed archive title to monospace
updated lists to open bullet

### CODE REVIEW

**Comment by nathanallen** [comment]
Your solution works... but _why_ and  _what_ was broken in the first place?

**Comment by nathanallen** [comment]
This is partially correct.
- Why are the bullets working just fine for all the other lists?

**Comment by samuel1008** [comment]
Updated users css file and _contents html line 3

**Comment by samuel1008** [comment]
Issue #1: Inconsistent Sidebar Styles

**Comment by samuel1008** [comment]
updated the html title on -content.html.erb
deleted extra code on user.css

**Comment by samuel1008** [comment]
fixed gemfile

**Comment by samuel1008** [comment]
changed archive title to monospace
updated lists to open bullet

**Pull request closed without merging**
