### PR TITLE
Fixed issue #7 - Sign-in form displays raw span html in input fields

### LINKED ISSUE #7: Sign-in form displays raw span html in input fields
The http://localhost:3000/users/sign_in page shows `<span class=` in the input fields, and other HTML "debris" below them.

See screenshot: 
screen shot 2016-02-04 at 7 29 18 pm

Expected behavior: 
Login field should say 'Login' (in english)
Password field should say 'Password' (in english)

Steps to reproduce:
1.  logout
2.  visit http://localhost:3000/users/sign_in
3.  view the form fields to sign-in

### PR DESCRIPTION
**Pull request by melicarls**
Fixes #7 
In app/views/devise/sessions/new.html.erb: 
- Replaced the placeholder for :login with the string 'Login'. Was t('.login') previously
- Replaced the placeholder for :password with the string 'Password'. Was t('.password') previously

### CODE REVIEW

**Comment by justincastilla** [comment]
Publify needs to be usable by an international audience of non-english speakers. Your are hardcoding the english words "Login" and "Password". Ignore Julia, good work!

**Comment by melicarls** [comment]
Fixes #7 
In app/views/devise/sessions/new.html.erb:
- Created labels with corresponding translations for form fields: 

```
<label for="login"><%= t('.login')%></label>
<%= f.text_field :login, class: 'form-control', autofocus: true %>
```

```
<label for="password"><%= t('.password')%></label>
<%= f.password_field :password, class: 'form-control', autocomplete: 'off' %>
```

**Comment by nathanallen** [comment]
I like that you're adding a label to your inputs, for accessibility reasons (a11y). But is the use of the `label` tag consistent with other forms on this site?

Also, please make sure there is placeholder text.

**Comment by melicarls** [comment]
Fixes #7 
-Removed <label> tags
-Added English language translations for 'Login' and 'Password' in en.yml. This would also need to be done for all other available languages. 

Added these lines of code to config/locales/en.yml:

```
  devise:
    sessions:
      new:
        login: Login
        password: Password
```

(I only figured this one out thanks to Brianna's hint on Slack!)

**Pull request closed without merging**
