### PR TITLE
Fixes issue #1 - changed sidebar styles: font style and bullet style

### PR DESCRIPTION
**Pull request by emilyannemoses**
Issue #1 :
- Changed CSS so all ul elements have circle styled bullet points for consistency with the rest of the bullet points
- Specified CSS so that all h3 elements have the same font style for consistency

### CODE REVIEW

**Comment by nathanallen** [comment]
This works, but... _why_ and _what_ was broken in the first place?

**Comment by emilyannemoses** [comment]
For Issue #1 : Aesthetic style issues

The font of each section of the side bar was incongruous. I chose to use the h3 element tag to select every text title so they would all be the same font. It was an aesthetic style issue.

The bullet points on the sidebar were two different styles - solid points and circles. I used the ul element selector in the CSS file and made all of them circles to be  more consistent with the style of the sidebar.

**Comment by justincastilla** [comment]
You are working in the San Francisco branch of Publify and only developers working in the Houston branch may work on the CSS files.

**Comment by nathanallen** [comment]
Agreed with @justincastilla. You are applying a new css style to a whole slew of list elements _that weren't broken in the first place_.

**Comment by emilyannemoses** [comment]
For issue #1 I created a new pull request for 
- Switched back the CSS to the way Huston prefers it to be (sorry Huston!) 
- Found and corrected inconsistent class names : sidebar_title to sidebar-title and sidebar_body to sidebar-body in the _content html.erb file.

**Pull request closed without merging**
